import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageShell } from '../components/PageShell'
import { SectionCard } from '../components/SectionCard'
import { createLrcImport, getJob } from '../lib/api'
import { loadWorkflow, saveWorkflow } from '../lib/workflow'

export function SpotifyLrcPreviewPage() {
  const { jobId = '' } = useParams()
  const navigate = useNavigate()
  const [lrcText, setLrcText] = useState('')
  const [lrcSourceLabel, setLrcSourceLabel] = useState('Generated by spotdl')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [workflow, setWorkflow] = useState(() => loadWorkflow())

  const jobQuery = useQuery({
    queryKey: ['job', jobId],
    queryFn: () => getJob(jobId),
    enabled: Boolean(jobId),
  })

  const result = jobQuery.data?.result
  const sourceId = typeof result?.sourceId === 'string' ? result.sourceId : workflow?.sourceId
  const generatedLrc = typeof result?.lrcText === 'string' ? result.lrcText : ''

  useEffect(() => {
    if (generatedLrc && !lrcText) {
      setLrcText(generatedLrc)
    }
  }, [generatedLrc, lrcText])

  async function handleCreatePlayer() {
    setError(null)
    if (!sourceId) {
      setError('Missing source id for this Spotify import.')
      return
    }
    if (!lrcText.trim()) {
      setError('Review or paste LRC text before creating the player.')
      return
    }

    setIsSubmitting(true)
    try {
      const lrcImport = await createLrcImport({
        sourceId,
        lrcText,
      })
      const nextWorkflow = {
        sourceId,
        sourceMode: 'spotify' as const,
        sourceJobId: jobId,
        lrcJobId: lrcImport.jobId,
      }
      setWorkflow(nextWorkflow)
      saveWorkflow(nextWorkflow)
      navigate(`/jobs/${lrcImport.jobId}`)
    } catch (submitError) {
      setError(submitError instanceof Error ? submitError.message : 'Failed to create LRC import job.')
    } finally {
      setIsSubmitting(false)
    }
  }

  async function handleLrcUpload(file: File | undefined) {
    if (!file) {
      return
    }
    setError(null)
    setLrcText(await file.text())
    setLrcSourceLabel(`Uploaded: ${file.name}`)
  }

  if (jobQuery.isLoading) {
    return (
      <PageShell
        eyebrow="Spotify LRC"
        title="Loading generated lyrics"
        subtitle="Fetching the spotdl import result before showing the editable LRC preview."
      />
    )
  }

  if (jobQuery.isError || !jobQuery.data) {
    return (
      <PageShell
        eyebrow="Spotify LRC"
        title="Preview unavailable"
        subtitle="The Spotify import job could not be loaded."
        aside={<Link className="secondary-button" to="/">Back to import</Link>}
      >
        <div className="error-state">{jobQuery.error instanceof Error ? jobQuery.error.message : 'Job not found.'}</div>
      </PageShell>
    )
  }

  return (
    <PageShell
      eyebrow="Spotify LRC Review"
      title="Confirm lyrics before building the player"
      subtitle="spotdl can return the wrong version. Use the generated LRC if it looks right, or upload a replacement LRC before creating the player."
      aside={<Link className="secondary-button" to="/">New import</Link>}
    >
      <div className="split-grid">
        <SectionCard title="LRC decision" subtitle="Choose whether to trust the generated LRC or replace it with a local file.">
          <div className="quick-list">
            <div className="detail-row">
              <span>Current LRC</span>
              <strong>{lrcText.trim() ? lrcSourceLabel : 'No LRC available'}</strong>
            </div>
            <div className="file-shell">
              <input
                className="file-input"
                type="file"
                accept=".lrc,text/plain"
                onChange={(event) => void handleLrcUpload(event.target.files?.[0])}
              />
              <span className="field-help">Choose a replacement `.lrc` file if the generated lyrics are the wrong version.</span>
            </div>
          </div>

          <div style={{ marginTop: 18 }}>
            <label className="field-label" htmlFor="lrc-editor">LRC text preview</label>
            <textarea
              id="lrc-editor"
              className="textarea"
              style={{ minHeight: 360 }}
              value={lrcText}
              onChange={(event) => setLrcText(event.target.value)}
              placeholder="Paste or edit LRC text here."
            />
            <p className="field-help">Use this for quick fixes only. Detailed line timing edits belong in a later player correction flow.</p>
          </div>

          {error ? <div className="error-state" style={{ marginTop: 16 }}>{error}</div> : null}
          <div className="actions" style={{ marginTop: 20 }}>
            <button className="primary-button" type="button" disabled={isSubmitting} onClick={handleCreatePlayer}>
              {isSubmitting ? 'Creating player...' : lrcSourceLabel.startsWith('Uploaded:') ? 'Create player from uploaded LRC' : 'Use this LRC and create player'}
            </button>
          </div>
        </SectionCard>

        <SectionCard title="Review checklist" subtitle="Use this step to catch provider mistakes before creating the song.">
          <div className="quick-list">
            <div className="detail-row">
              <span>Source id</span>
              <span className="inline-code">{sourceId ?? 'missing'}</span>
            </div>
            <div className="metric">
              <strong>Minor typo?</strong>
              <span className="muted">It is OK to continue and handle fine-grained lyric correction later in the player.</span>
            </div>
          </div>
        </SectionCard>
      </div>
    </PageShell>
  )
}
